#!/usr/bin/env bash

# Figure out if we need sudo or not
sudo=''
if [[ $EUID -ne 0 ]]; then
  sudo='sudo'
fi

# Download script from Github
echo "=== Saving executable to /usr/local/bin/respec"
curl_command="curl -s https://raw.githubusercontent.com/DannyBen/respec/master/respec > /usr/local/bin/respec"
$sudo bash -c "$curl_command"
$sudo chmod a+x /usr/local/bin/respec

# Install completions
if [[ -d "/usr/share/bash-completion/completions" ]]; then
  compdir="/usr/share/bash-completion/completions"
elif [[ -d "/usr/local/etc/bash_completion.d" ]]; then
  compdir="/usr/local/etc/bash_completion.d"
elif command -v brew &>/dev/null && [[ -d "$(brew --prefix)/etc/bash_completion.d" ]]; then
  compdir="$(brew --prefix)/etc/bash_completion.d"
else
  compdir=''
fi

if [[ -n $compdir ]]; then
  echo "=== Installing autocompletions to $compdir"
  echo "eval \"\$(respec completions)\"" | $sudo tee "${compdir}/respec" > /dev/null
else
  echo "=== Completion script was not installed"
  echo "    To install it manually add this to your startup script:"
  echo "    eval \"\$(respec completions)\""
fi

# Verify
if type respec > /dev/null; then
  echo "=== Done. Type 'respec' for more info."
else
  echo "=== Setup failed."
  exit 1
fi
