#!/usr/bin/env bash

# Figure out if we need sudo or not
sudo=''
if [[ $EUID -ne 0 ]]; then
  sudo='sudo'
fi

# Remove executable
echo "=== Removing executable from /usr/local/bin/respec"
$sudo rm -f /usr/local/bin/respec

# Remove completions
if [[ -d "/usr/share/bash-completion/completions" ]]; then
  compdir="/usr/share/bash-completion/completions"
elif [[ -d "/usr/local/etc/bash_completion.d" ]]; then
  compdir="/usr/local/etc/bash_completion.d"
elif command -v brew &>/dev/null && [[ -d "$(brew --prefix)/etc/bash_completion.d" ]]; then
  compdir="$(brew --prefix)/etc/bash_completion.d"
else
  compdir=''
fi

if [[ -n $compdir ]]; then
  echo "=== Removing autocompletions from $compdir"
  $sudo rm -f "${compdir}/respec"
else
  echo "=== Completion script was not removed"
  echo "    Remove it manually from your startup script:"
  echo "    eval \"\$(respec completions)\""
fi

# Verify
if type respec > /dev/null; then
  echo "=== Uninstall failed."
  exit 1
else
  echo "=== Done."
fi
